//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelamientoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIENTO_EVENTO
    {
        public int CASiento { get; set; }
        public int CEvento { get; set; }
        public Nullable<int> CEstadoAsiento { get; set; }
    
        public virtual ASIENTO ASIENTO { get; set; }
        public virtual EVENTO EVENTO { get; set; }
        public virtual ESTADOASIENTO ESTADOASIENTO { get; set; }
    }
}
