//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelamientoDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTeatroEntities : DbContext
    {
        public DBTeatroEntities()
            : base("name=DBTeatroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASIENTO> ASIENTO { get; set; }
        public DbSet<ASIENTO_EVENTO> ASIENTO_EVENTO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ESTADOASIENTO> ESTADOASIENTO { get; set; }
        public DbSet<EVENTO> EVENTO { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TIPO_ASIENTO> TIPO_ASIENTO { get; set; }
        public DbSet<TIPOEMPLEADO> TIPOEMPLEADO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
    }
}
