//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelamientoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOEMPLEADO
    {
        public TIPOEMPLEADO()
        {
            this.EMPLEADO = new HashSet<EMPLEADO>();
        }
    
        public int CTipoEmpleado { get; set; }
        public string NTipoEmpleado { get; set; }
    
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    }
}
