select *from ASIENTO


select *from TIPO_ASIENTO

INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('ORO',40,'ROJO','ZONA PITUCA')

INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('SUPER',35,'AZUL','ZONA MENOS PITUCA')



INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('VIP',30,'VERDE','ZONA MENOS MENOS PITUCA')

INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('PLATINUM',20,'ROJO MUERTO','MASOMENOS')

INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('PREFERENCIAL',18,'MORADO','MENOS MASOMENOS')

INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('BASICO',15,'ROJA','POPULARXD')

INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('POPULAR',10,'ROJA','PROPIAMENTE POPULARXD')

INSERT INTO TIPO_ASIENTO(NTipoAsiento,Precio,NColor,TDescripcion)
VALUES('BLOQUEADO',0,'PLOMO','BLOQUEADO')

UPDATE  TIPO_ASIENTO SET NColor='AMARILLA' WHERE CTipoAsiento=7

