//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIENTO
    {
        public ASIENTO()
        {
            this.ASIENTO_EVENTO = new HashSet<ASIENTO_EVENTO>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int CASiento { get; set; }
        public string Letra { get; set; }
        public int Numero { get; set; }
        public Nullable<int> CTipoAsiento { get; set; }
    
        public virtual TIPO_ASIENTO TIPO_ASIENTO { get; set; }
        public virtual ICollection<ASIENTO_EVENTO> ASIENTO_EVENTO { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
