//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public EVENTO()
        {
            this.ASIENTO_EVENTO = new HashSet<ASIENTO_EVENTO>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public string NEvento { get; set; }
        public int CEvento { get; set; }
        public System.DateTime DFechaEvento { get; set; }
        public string TDescripcion { get; set; }
    
        public virtual ICollection<ASIENTO_EVENTO> ASIENTO_EVENTO { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
