//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ASIENTO
    {
        public TIPO_ASIENTO()
        {
            this.ASIENTO = new HashSet<ASIENTO>();
        }
    
        public int CTipoAsiento { get; set; }
        public string NTipoAsiento { get; set; }
        public double Precio { get; set; }
        public string NColor { get; set; }
        public string TDescripcion { get; set; }
    
        public virtual ICollection<ASIENTO> ASIENTO { get; set; }
    }
}
