//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int CUsuario { get; set; }
        public string NNombres { get; set; }
        public string NAPellidos { get; set; }
        public string DNI { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string TDireccion { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
