//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.ASIENTO = new HashSet<ASIENTO>();
        }
    
        public int CVenta { get; set; }
        public double MontoTotal { get; set; }
        public System.DateTime DFechaVenta { get; set; }
        public Nullable<int> CUsuario { get; set; }
        public int CEmpleado { get; set; }
        public Nullable<int> CCliente { get; set; }
        public int CEvento { get; set; }
        public string FBoleta { get; set; }
        public string FFactura { get; set; }
        public string RUC { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual EVENTO EVENTO { get; set; }
        public virtual ICollection<ASIENTO> ASIENTO { get; set; }
    }
}
